version: '3.8'

services:
  rtmp-server:
    image: tiangolo/nginx-rtmp
    container_name: rtmp-server
    ports:
      - "1935:1935" # RTMP port
      - "8080:80"   # HTTP stats page
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
